'''
This is the Settings File for the Mattermost-Octane Bridge.
You can change various variables here to customize and set up the client.
'''


'''----------------------Mattermost Webhook Configuration----------------------'''

#URL of the webhook from mattermost. To create one go to `Main Menu -> Integrations -> Incoming Webhooks` and press `Add Incoming Webhook`
mm_webhook_url = 'http://localhost:8065/hooks/yuro8xrfeffj787cj1bwc4ziue'

#Override the channel to send the notifications to, use the channel name as a String
mm_channel = None

#Set a custom Username to display in Mattermost
mm_username = 'Defect Notification'

#Set a custom Profile Image for the Client
mm_profileimage = 'https://i.imgur.com/7Wg3Tgs.png' #Telekom T Image

#The latter two need to be enabled in the settings.json of the Mattermost server


'''----------------------------Flask Configuration----------------------------'''


#set external IP for the Flask Server to create a Webhook for ALM Octane
#local: 127.0.0.1 / False
#default external: 0.0.0.0 (will default to only available external adress)
external_ip = False

#default: 5000
port = 5000

#external webhook verify token can be set here, if set as `None` it will be autogenerated & changed on each startup.
wh_token = None
